
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "github.com/creack/termios"
  branch = "master"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/mcuadros/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/ontariosystems/isclib"
  version = "^2.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "^0.5.2"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"